<a href="https://colab.research.google.com/github/smohamadabedy/DataScience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import math

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

ndarray (alias array)

Props:
* darray.ndim
* ndarray.shape
* ndarray.size
* ndarray.dtype


In [32]:
#define as np.array( [ [] , [] , .... ] , dtype= )
array1 = np.array([[1,2,3],[3,4,5],[6,7,8]]);

print(array1)
print(array1.size)
print(array1.shape)
print(array1.ndim)
print(array1.dtype,np.array([1.2344,math.sqrt(2)]).dtype)
print(np.array([1.2344,math.sqrt(2)], dtype=int))
# reshape
print(array1.reshape(-1,1))
print(array1.reshape(9,1))
print(array1.reshape(1,-1))
print(array1.reshape(1,9))


[[1 2 3]
 [3 4 5]
 [6 7 8]]
9
(3, 3)
2
int64 float64
[1 1]
[[1]
 [2]
 [3]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1]
 [2]
 [3]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3 3 4 5 6 7 8]]
[[1 2 3 3 4 5 6 7 8]]


In [53]:
print(np.sin(1),
      np.exp(2),
      np.linspace(0,np.pi,5),
      np.logspace(0,2,5),
      np.arange(0,np.pi,.1),
      np.ones(5),
      np.zeros(5),
      np.empty(5),
      np.random.random((3,2))

      )

0.8414709848078965 7.38905609893065 [0.         0.78539816 1.57079633 2.35619449 3.14159265] [  1.           3.16227766  10.          31.6227766  100.        ] [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1] [1. 1. 1. 1. 1.] [0. 0. 0. 0. 0.] [0. 0. 0. 0. 0.] [[0.34918367 0.44500466]
 [0.48330459 0.9334332 ]
 [0.82692984 0.4136685 ]]


In [50]:
# element wise
# caution! if dimentions are mismatched then utilize Broadcasting
np.array([1,2])*np.array([[3,4],[5,6]])

array([[ 3,  8],
       [ 5, 12]])